@echo off
mkdir build
echo Building INVITE...
bin\beebasm.exe -i src\invite.asm -v > build\invite.txt
echo Building MUSIC...
bin\beebasm.exe -i src\music.asm -v > build\music.txt
echo Building DISC...
bin\beebasm.exe -i disc-build.asm -do build\nova-invite.ssd -title NOVA-INVITE -opt 2 -v > compile.txt
